name: EsLint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install eslint last version
        run: npm install eslint --global

      - name: install config
        run: npm init @eslint/config

      # Runs a set of commands using the runners shell
      - name: Run ESLint
        run: eslint *.js
