name: Unit-Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: package.json
        run: test -f package.json || npm init -y
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
